#!/bin/sh
# Start/stop the NZBget daemon.
#
case "$1" in
start)   echo -n "Start services: NZBget"
   su -s /bin/bash -c "/usr/bin/nzbget -D" {{ nzbget_user }}
   ;;
stop)   echo -n "Stop services: NZBget"
   su -s /bin/bash -c "/usr/bin/nzbget -Q" {{ nzbget_user }}
   ;;
restart)
   $0 stop
   $0 start
        ;;
*)   echo "Usage: $0 start|stop|restart"
        exit 1
        ;;
esac
exit 0
