##########################################################################
# Machination
# Copyright (c) 2015, Alexandre ACEBEDO, All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library.
##########################################################################
 
  - name: Add multiverse repository
    apt_repository: repo="{{ item }}"
    register: multiverse_installed
    with_items:
     - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse"
     - "deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse"
     - "deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse"
     - "deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse"

  - name: Update apt cache
    apt: update_cache= true
    when: multiverse_installed | changed

  - name: Add seedboxers group
    group: name="{{ transmission_group }}" state=present

  - name: Install transmission
    apt: name="{{ item }}" state=present
    with_items:
      - transmission-daemon

  - name: Create dst dir
    file: path="{{ transmission_dst_path }}" owner=debian-transmission group="{{ transmission_group }}" state=directory
  
  - name: Add transmission user
    user: name=debian-transmission group="{{ transmission_group }}" state=present system=yes shell=/sbin/nologin
  
  - name: Add configuration file
    template: src=settings.json dest=/etc/transmission-daemon/settings.json owner=debian-transmission group="{{ transmission_group }}" mode="755"

  - name: Start service
    service: name=transmission-daemon state=started
    
  - name: Add service to startup
    shell: sudo update-rc.d transmission-daemon defaults
   
