  - name: Update apt cache
    apt: update_cache=yes

  - name: Download plex
    get_url: url={{ plex_deb_url }} dest=/tmp/plex.deb

  - name: Install plex
    apt: deb=/tmp/plex.deb  state=installed
