 
  - name: Add multiverse repository
    apt_repository: repo="{{item}}"
    register: multiverse_installed
    with_items:
     - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
     - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
     - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
     - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

  - name: Update apt cache
    apt: update_cache= true
    when: multiverse_installed | changed

  - name: Add seedboxers group
    group: name=seedboxers state=present gid=10000

  - name: Add transmission user
    user: name=transmission group=seedboxers home=/usr/local/share/transmission state=present system=yes shell=/sbin/nologin

  - name: Install transmission
    apt: name={{ item }} state=present
    with_items:
      - transmission-daemon
  
  - name: Add configuration file
    copy: src=settings.json dest=/etc/transmission-daemon/settings.json owner=transmission group=seedboxers

  - name: Start service
    service: name=transmission-daemon state=started
   
