##########################################################################
# Machination
# Copyright (c) 2015, Alexandre ACEBEDO, All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library.
##########################################################################
 
  - name: Add multiverse repository
    apt_repository: repo="{{item}}"
    register: multiverse_installed
    with_items:
     - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
     - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse'
     - 'deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'
     - 'deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse'

  - name: Update apt cache
    apt: update_cache= true
    when: multiverse_installed | changed

  - name: Install python dependencies
    apt: name={{ item }} state=present
    with_items:
      - git-core
      - python
      - python-cheetah

  - name: Install utilities
    apt: name={{ item }} state=present
    with_items:
      - unzip
      - unrar

  - name: Add seedboxers group
    group: name=seedboxers state=present gid=10000

  - name: Add sickrage user
    user: name=sickrage group=seedboxers home=/usr/local/share/sickrage state=present system=yes shell=/sbin/nologin

  - name: Clone sickrage
    git: repo=git://github.com/echel0n/SickRage.git dest=/opt/sickrage accept_hostkey=true
 
  - name: Change owner of sickrage folder
    file: path=/opt/sickrage recurse=true owner=sickrage group=seedboxers

  - name: Copy init script
    command: cp /opt/sickrage/init.ubuntu /etc/init.d/sickbeard

  - name: Change owner of init script
    file: path=/etc/init.d/sickbeard mode="755" owner="root" group="root"

  - name: Add script to startup
    command: update-rc.d sickbeard defaults

  - name: Add sickrage config file
    copy: src=sickbeard dest=/etc/default/sickbeard

  - name: Start service
    service: name=sickbeard state=started
