##########################################################################
# Machination
# Copyright (c) 2015, Alexandre ACEBEDO, All rights reserved.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3.0 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library.
##########################################################################


  - name: Add user to dialout group
    user: name="{{ arduino_user }}" group=dialout state=present
  
  - name: Download arduino dev framework
    get_url: url="http://downloads.arduino.cc/{{ arduino_dev_tools_env_version }}-linux64.tar.xz" dest=/tmp/arduino.tar.gz
  
  - name: Unzip donwloaded framework
    unarchive: src=/tmp/arduino.tar.gz dest="{{ arduino_dev_tools_env_path }}"
    
  - name: link to arduino tools
    shell:  "ln -s {{ arduino_dev_tools_env_path }}/{{ arduino_dev_tools_env_version }}/hardware/tools/avr/bin/* /bin && ln -s /opt/{{ arduino_dev_tools_env_version }}/hardware/tools/avr/etc/* /etc" 
    
  - name: Install eclipse plugin
    shell: "{{ arduino_dev_tools_eclipse_path }}/eclipse -nosplash 
    -application org.eclipse.equinox.p2.director 
    -repository http://www.baeyens.it/eclipse/V2 -destination {{ arduino_dev_tools_eclipse_path }} 
    -installIU it.baeyens.arduino.feature.feature.group"