  - name: Update apt cache
    apt: update_cache=yes

  - name: Install nginx
    apt: name=nginx state=present

  - name: Install php
    apt: name={{ item }} state=present
    with_items:
      - php5-gd
      - php5-fpm 
      - libssh2-php
      - php5-sqlite
      - sqlite

  - name: Download wordpress
    get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz

  - name: Create www directory
    file: path=/var/www/ state=directory 
 
  - name: Extract wordpress
    command: tar xvzf /tmp/latest.tar.gz chdir=/var/www/

  - name: Copy site files
    command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/wordpress

  - name: Change website root
    copy: src=./wordpress/files/wordpress dest=/etc/nginx/sites-available/wordpress

  - name: Create symlink
    file: dest=/etc/nginx/sites-enabled/wordpress src=/etc/nginx/sites-available/wordpress state=link
 
  - name: Get SQLite plugin for wordpress
    get_url: url=http://downloads.wordpress.org/plugin/sqlite-integration.1.7.zip dest=/tmp/sqlite-integration.zip 

  - name: Unzip SQLite plugin
    command: unzip -o /tmp/sqlite-integration.zip -d /var/www/wordpress/wp-content/plugins

  - name: Copy db.php file
    command: cp /var/www/wordpress/wp-content/plugins/sqlite-integration/db.php /var/www/wordpress/wp-content

  - name: Copy wp-config.php file
    command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

  - name: Change owner
    file: path=/var/www owner=www-data group=www-data recurse=yes


